/**
 * Seeds the intellectual library: philosophy fragments, historical insights,
 * psychological observations, deep essays — all with real source attribution.
 *
 * Idempotent: each entry has a deterministic externalId so re-running won't
 * create duplicates.
 *
 * Run: pnpm --filter @workspace/scripts run seed:library
 */
import { db, articlesTable } from "@workspace/db";
import { sql } from "drizzle-orm";

type Seed = {
  externalId: string;
  categorySlug: string;
  contentType: "philosophy" | "historical" | "psychology" | "essay" | "quote" | "geopolitical" | "market_signal" | "culture" | "technology";
  headline: string;
  summary: string;
  whyItMatters: string;
  facts: string[];
  source: string;
  sourceUrl: string;
  author?: string;
  historicalDate?: string;
  tags: string[];
  icon: string;
  sentiment: string;
  impactLevel?: "high" | "medium" | "low";
  imageUrl?: string;
  publishedYearsAgo?: number;
};

const LIBRARY: Seed[] = [
  // ── PHILOSOPHY ──────────────────────────────────────────────────────────
  {
    externalId: "lib-nietzsche-abyss",
    categorySlug: "psychology",
    contentType: "philosophy",
    author: "Friedrich Nietzsche",
    historicalDate: "1886",
    headline: "He who fights with monsters",
    summary: "“He who fights with monsters should look to it that he himself does not become a monster. And if you gaze long into an abyss, the abyss also gazes into you.”",
    whyItMatters: "Nietzsche's warning — written in the wake of European nihilism — is now read as the founding metaphor for moral hazard in surveillance, war, and platform moderation. The structure of opposition tends to mirror itself.",
    facts: [
      "Source: Beyond Good and Evil, Aphorism 146 (1886).",
      "Original German: ‘Wer mit Ungeheuern kämpft, mag zusehn, dass er nicht dabei zum Ungeheuer wird.’",
      "Translation: Walter Kaufmann, Vintage, 1966.",
    ],
    source: "Nietzsche, Beyond Good and Evil §146",
    sourceUrl: "https://www.gutenberg.org/files/4363/4363-h/4363-h.htm",
    tags: ["nietzsche", "ethics", "self-knowledge"],
    icon: "❖",
    sentiment: "Reflective",
    impactLevel: "medium",
  },
  {
    externalId: "lib-camus-sisyphus",
    categorySlug: "psychology",
    contentType: "philosophy",
    author: "Albert Camus",
    historicalDate: "1942",
    headline: "One must imagine Sisyphus happy",
    summary: "Camus closes his essay with the proposition that the absurd hero, condemned to ceaseless labour without meaning, finds dignity in the struggle itself — not in any reward beyond it.",
    whyItMatters: "The Myth of Sisyphus reframed despair as a creative position. It is the philosophical underpinning behind modern thought on burnout, climate fatalism, and the search for meaning in repetitive work.",
    facts: [
      "Source: Le Mythe de Sisyphe, Gallimard, 1942.",
      "English translation: Justin O'Brien, Hamish Hamilton, 1955.",
      "Camus was 28 when he wrote it; awarded the Nobel Prize in Literature in 1957.",
    ],
    source: "Camus, The Myth of Sisyphus",
    sourceUrl: "https://en.wikipedia.org/wiki/The_Myth_of_Sisyphus",
    tags: ["camus", "absurdism", "meaning"],
    icon: "❖",
    sentiment: "Stoic",
    impactLevel: "medium",
  },
  {
    externalId: "lib-kierkegaard-anxiety",
    categorySlug: "psychology",
    contentType: "philosophy",
    author: "Søren Kierkegaard",
    historicalDate: "1844",
    headline: "Anxiety is the dizziness of freedom",
    summary: "Kierkegaard distinguishes anxiety (Angst) from fear: fear has an object, anxiety has none. It is the vertigo a person feels when staring at the open possibilities of their own choosing.",
    whyItMatters: "This single sentence laid the groundwork for 20th-century existentialism and modern psychiatric understanding of generalised anxiety. Heidegger, Sartre and Tillich all build on it.",
    facts: [
      "Source: The Concept of Anxiety, 1844 (Begrebet Angest).",
      "Pseudonym used: Vigilius Haufniensis.",
      "Translated by Reidar Thomte for Princeton University Press, 1980.",
    ],
    source: "Kierkegaard, The Concept of Anxiety",
    sourceUrl: "https://plato.stanford.edu/entries/kierkegaard/",
    tags: ["kierkegaard", "existentialism", "anxiety"],
    icon: "❖",
    sentiment: "Reflective",
    impactLevel: "medium",
  },
  {
    externalId: "lib-wittgenstein-limits",
    categorySlug: "tech",
    contentType: "philosophy",
    author: "Ludwig Wittgenstein",
    historicalDate: "1921",
    headline: "The limits of my language mean the limits of my world",
    summary: "Proposition 5.6 of the Tractatus argues that what cannot be expressed in language cannot be thought clearly — a claim that haunts every debate about machine intelligence and the boundaries of representation.",
    whyItMatters: "LLMs make Wittgenstein's claim newly empirical: they think only in the language we give them. The proposition is now central to AI alignment, model interpretability, and translation studies.",
    facts: [
      "Source: Tractatus Logico-Philosophicus, proposition 5.6 (1921).",
      "First published in Annalen der Naturphilosophie; English edition 1922.",
      "Wittgenstein later partly repudiated the Tractatus in Philosophical Investigations (1953).",
    ],
    source: "Wittgenstein, Tractatus Logico-Philosophicus",
    sourceUrl: "https://www.gutenberg.org/ebooks/5740",
    tags: ["wittgenstein", "language", "ai"],
    icon: "❖",
    sentiment: "Analytical",
    impactLevel: "medium",
  },
  {
    externalId: "lib-arendt-banality",
    categorySlug: "society",
    contentType: "philosophy",
    author: "Hannah Arendt",
    historicalDate: "1963",
    headline: "The banality of evil",
    summary: "Reporting on the Eichmann trial in Jerusalem, Arendt argued that the worst atrocities are not committed by monsters but by ordinary administrators incapable of independent moral thought.",
    whyItMatters: "Arendt's phrase reframed how democracies think about bureaucratic complicity, from war crimes to algorithmic harm. It remains the most quoted political-philosophical idea of the 20th century.",
    facts: [
      "Source: Eichmann in Jerusalem: A Report on the Banality of Evil, Viking Press, 1963.",
      "Originally published as a five-part series in The New Yorker.",
      "Arendt fled Nazi Germany in 1933 and reported the trial for the magazine in 1961.",
    ],
    source: "Arendt, Eichmann in Jerusalem",
    sourceUrl: "https://www.newyorker.com/magazine/1963/02/16/eichmann-in-jerusalem-i",
    tags: ["arendt", "ethics", "politics"],
    icon: "❖",
    sentiment: "Critical",
    impactLevel: "high",
  },
  {
    externalId: "lib-marx-circumstances",
    categorySlug: "society",
    contentType: "philosophy",
    author: "Karl Marx",
    historicalDate: "1852",
    headline: "Men make their own history, but not as they please",
    summary: "Marx opens The Eighteenth Brumaire with the claim that historical actors inherit the conditions of their action — a corrective to both Hegelian idealism and naive voluntarism.",
    whyItMatters: "The line is the most concise statement of structural agency in social theory and a touchstone for everything from path-dependency in economics to the sociology of technology.",
    facts: [
      "Source: The Eighteenth Brumaire of Louis Bonaparte, 1852.",
      "Originally serialised in Die Revolution, New York.",
      "Full quote ends: ‘…but under circumstances directly encountered, given and transmitted from the past.’",
    ],
    source: "Marx, The Eighteenth Brumaire",
    sourceUrl: "https://www.marxists.org/archive/marx/works/1852/18th-brumaire/",
    tags: ["marx", "history", "structure"],
    icon: "❖",
    sentiment: "Analytical",
    impactLevel: "medium",
  },
  {
    externalId: "lib-sartre-condemned",
    categorySlug: "psychology",
    contentType: "philosophy",
    author: "Jean-Paul Sartre",
    historicalDate: "1946",
    headline: "Man is condemned to be free",
    summary: "In his post-war lecture, Sartre argues that without divine sanction or fixed essence, human beings carry the entire weight of their choices — a freedom that is both gift and verdict.",
    whyItMatters: "The lecture popularised existentialism for a generation. It remains the clearest entry-point for questions of moral responsibility in secular life.",
    facts: [
      "Source: L'existentialisme est un humanisme, lecture given at Club Maintenant, Paris, 28 October 1945.",
      "Published 1946 by Les Éditions Nagel.",
      "Translated by Carol Macomber, Yale University Press, 2007.",
    ],
    source: "Sartre, Existentialism is a Humanism",
    sourceUrl: "https://plato.stanford.edu/entries/sartre/",
    tags: ["sartre", "freedom", "existentialism"],
    icon: "❖",
    sentiment: "Reflective",
    impactLevel: "medium",
  },
  {
    externalId: "lib-confucius-mistakes",
    categorySlug: "psychology",
    contentType: "philosophy",
    author: "Confucius",
    historicalDate: "0500",
    headline: "When you know a thing",
    summary: "“When you know a thing, to hold that you know it; and when you do not know a thing, to allow that you do not know it — this is knowledge.”",
    whyItMatters: "The Confucian definition of intellectual honesty pre-dates Socrates by a century and remains the operating standard of empirical science and good editing.",
    facts: [
      "Source: Analects, Book II, Chapter 17 (~500 BCE).",
      "Translation: James Legge, Oxford, 1893.",
      "Compiled by disciples of Confucius after his death in 479 BCE.",
    ],
    source: "Confucius, Analects II.17",
    sourceUrl: "https://ctext.org/analects/wei-zheng",
    tags: ["confucius", "epistemology", "humility"],
    icon: "❖",
    sentiment: "Reflective",
    impactLevel: "low",
  },

  // ── PSYCHOLOGY ──────────────────────────────────────────────────────────
  {
    externalId: "lib-jung-shadow",
    categorySlug: "psychology",
    contentType: "psychology",
    author: "Carl Gustav Jung",
    historicalDate: "1951",
    headline: "Until you make the unconscious conscious",
    summary: "Jung's claim that unintegrated material from the unconscious will be projected outward and experienced as fate is the founding insight of depth psychology.",
    whyItMatters: "The mechanism Jung described — projection of unowned content — is now visible at scale in social media discourse, where group identity becomes a screen for individual shadow material.",
    facts: [
      "Source: Aion: Researches into the Phenomenology of the Self, Collected Works Vol. 9 Part II, 1951.",
      "First published in German by Rascher Verlag, Zürich.",
      "Princeton University Press / Bollingen Series edition translated by R.F.C. Hull.",
    ],
    source: "Jung, Aion (Collected Works Vol. 9.II)",
    sourceUrl: "https://en.wikipedia.org/wiki/Aion:_Researches_into_the_Phenomenology_of_the_Self",
    tags: ["jung", "shadow", "projection"],
    icon: "◐",
    sentiment: "Reflective",
    impactLevel: "medium",
  },
  {
    externalId: "lib-frankl-meaning",
    categorySlug: "psychology",
    contentType: "psychology",
    author: "Viktor Frankl",
    historicalDate: "1946",
    headline: "Between stimulus and response there is a space",
    summary: "Frankl, a survivor of four concentration camps, observed that the last human freedom is the choice of one's attitude in any given set of circumstances — the foundation of logotherapy.",
    whyItMatters: "Logotherapy reframed psychiatric practice around the search for meaning rather than the management of symptoms. It anticipated modern findings on stoic appraisal in CBT and PTSD treatment.",
    facts: [
      "Source: Man's Search for Meaning, Beacon Press, 1946 (orig. Ein Psycholog erlebt das Konzentrationslager).",
      "Sold over 16 million copies in 50+ languages.",
      "Frankl founded the Third Viennese School of Psychotherapy.",
    ],
    source: "Frankl, Man's Search for Meaning",
    sourceUrl: "https://www.viktorfrankl.org/",
    tags: ["frankl", "meaning", "resilience"],
    icon: "◐",
    sentiment: "Stoic",
    impactLevel: "high",
  },
  {
    externalId: "lib-james-attention",
    categorySlug: "psychology",
    contentType: "psychology",
    author: "William James",
    historicalDate: "1890",
    headline: "My experience is what I agree to attend to",
    summary: "James's chapter on attention argues that selective focus is the single most important determinant of subjective reality — what we attend to literally constitutes our world.",
    whyItMatters: "This sentence is the philosophical basis of the modern attention economy. Every recommendation algorithm now competes for the resource James identified 130 years ago.",
    facts: [
      "Source: The Principles of Psychology, Vol. 1, Chapter XI, 1890.",
      "Published by Henry Holt and Company.",
      "Foundational text of American functional psychology.",
    ],
    source: "James, The Principles of Psychology",
    sourceUrl: "https://psychclassics.yorku.ca/James/Principles/prin11.htm",
    tags: ["james", "attention", "consciousness"],
    icon: "◐",
    sentiment: "Reflective",
    impactLevel: "medium",
  },
  {
    externalId: "lib-kahneman-systems",
    categorySlug: "psychology",
    contentType: "psychology",
    author: "Daniel Kahneman",
    historicalDate: "2011",
    headline: "Two systems, one mind",
    summary: "Kahneman synthesises four decades of research into a single proposition: cognition runs on two interleaved systems — fast, automatic, intuitive judgment, and slow, effortful, deliberate reasoning.",
    whyItMatters: "The framework is the most consequential popular theory of mind since Freud's, structuring how policymakers, designers, and physicians now think about choice, error and bias.",
    facts: [
      "Source: Thinking, Fast and Slow, Farrar, Straus and Giroux, 2011.",
      "Kahneman won the Nobel Memorial Prize in Economics in 2002 (with Vernon Smith).",
      "His prospect theory paper with Amos Tversky (1979) is the most-cited in economics.",
    ],
    source: "Kahneman, Thinking, Fast and Slow",
    sourceUrl: "https://en.wikipedia.org/wiki/Thinking,_Fast_and_Slow",
    tags: ["kahneman", "cognition", "behavioural-economics"],
    icon: "◐",
    sentiment: "Analytical",
    impactLevel: "high",
  },
  {
    externalId: "lib-dunbar-150",
    categorySlug: "psychology",
    contentType: "psychology",
    author: "Robin Dunbar",
    historicalDate: "1992",
    headline: "The cognitive limit on social relationships",
    summary: "Dunbar, an evolutionary anthropologist, proposed that the size of the human neocortex constrains the number of stable social relationships an individual can maintain — approximately 150.",
    whyItMatters: "‘Dunbar's number’ is now the most cited constant in network design, military unit size, and social-platform research. It explains why scaled human cooperation requires institutions, not friendship.",
    facts: [
      "Source: Dunbar, R.I.M. (1992), ‘Neocortex size as a constraint on group size in primates’, Journal of Human Evolution 22(6).",
      "Range: 100–250; 150 is the modal estimate.",
      "Subsequent work identifies layered circles at 5, 15, 50, 150, 500, 1500.",
    ],
    source: "Dunbar (1992), J. Human Evolution",
    sourceUrl: "https://doi.org/10.1016/0047-2484(92)90081-J",
    tags: ["dunbar", "anthropology", "networks"],
    icon: "◐",
    sentiment: "Analytical",
    impactLevel: "medium",
  },

  // ── HISTORICAL INSIGHT ──────────────────────────────────────────────────
  {
    externalId: "lib-hist-thucydides-trap",
    categorySlug: "geopolitics",
    contentType: "historical",
    author: "Thucydides",
    historicalDate: "0431",
    headline: "What made war inevitable was the growth of Athenian power",
    summary: "Thucydides identified a recurring pattern: when a rising power threatens to displace an established one, war is the most common — though not inevitable — outcome.",
    whyItMatters: "Graham Allison's 2017 study found 12 of 16 historical cases of this dynamic ended in war. The framing now structures every serious analysis of US–China competition.",
    facts: [
      "Source: History of the Peloponnesian War, Book I, Chapter 23 (~431 BCE).",
      "Translation: Richard Crawley, 1874.",
      "Modern restatement: Graham Allison, Destined for War (2017), Houghton Mifflin Harcourt.",
    ],
    source: "Thucydides, History I.23",
    sourceUrl: "https://www.gutenberg.org/files/7142/7142-h/7142-h.htm",
    tags: ["thucydides", "geopolitics", "great-powers"],
    icon: "◈",
    sentiment: "Cautionary",
    impactLevel: "high",
  },
  {
    externalId: "lib-hist-bretton-woods",
    categorySlug: "finance",
    contentType: "historical",
    author: "John Maynard Keynes",
    historicalDate: "1944",
    headline: "Bretton Woods: the architecture of post-war money",
    summary: "In July 1944, delegates from 44 nations met at Mount Washington Hotel to design the post-war monetary order — fixed exchange rates anchored to the dollar, dollar convertible to gold at $35/oz.",
    whyItMatters: "The system collapsed when Nixon closed the gold window in 1971, but its institutions — the IMF and World Bank — still shape capital flows. Today's debate on a multipolar reserve currency is a Bretton Woods echo.",
    facts: [
      "Conference dates: 1–22 July 1944.",
      "Keynes proposed an international clearing union and a synthetic currency, the ‘bancor’; the US-backed White Plan won.",
      "Source: Benn Steil, The Battle of Bretton Woods (Princeton, 2013); IMF official history.",
    ],
    source: "IMF Archives & Steil (2013)",
    sourceUrl: "https://www.imf.org/external/np/exr/center/mm/eng/mm_dr_01.htm",
    tags: ["bretton-woods", "monetary", "history"],
    icon: "◈",
    sentiment: "Analytical",
    impactLevel: "high",
  },
  {
    externalId: "lib-hist-printing-press",
    categorySlug: "tech",
    contentType: "historical",
    author: "Elizabeth Eisenstein",
    historicalDate: "1450",
    headline: "Gutenberg: the unintended Reformation",
    summary: "Johannes Gutenberg's movable-type press, completed around 1450 in Mainz, did not set out to fracture Christendom — but within seventy years it had enabled Luther's 95 Theses to circulate Europe in weeks.",
    whyItMatters: "Eisenstein's two-volume study established that media revolutions reshape institutions on a generational lag. The pattern recurs with radio, television, the web, and now generative AI.",
    facts: [
      "Source: Elizabeth Eisenstein, The Printing Press as an Agent of Change, Cambridge University Press, 1979.",
      "Gutenberg's 42-line Bible was completed c. 1455; ~180 copies printed, 49 survive.",
      "Estimated European print output: ~20 million books in the 15th century, ~200 million in the 16th.",
    ],
    source: "Eisenstein, The Printing Press as an Agent of Change",
    sourceUrl: "https://www.cambridge.org/core/books/printing-press-as-an-agent-of-change/",
    tags: ["printing", "media", "reformation"],
    icon: "◈",
    sentiment: "Analytical",
    impactLevel: "medium",
  },
  {
    externalId: "lib-hist-nixon-shock",
    categorySlug: "finance",
    contentType: "historical",
    author: "Richard Nixon",
    historicalDate: "1971",
    headline: "The Nixon Shock and the end of the gold dollar",
    summary: "On 15 August 1971, President Nixon announced the suspension of the dollar's convertibility into gold — ending the Bretton Woods system and inaugurating the era of pure fiat currency.",
    whyItMatters: "Every modern macroeconomic instrument — central bank balance-sheet expansion, floating exchange rates, sovereign debt cycles — descends from this single Sunday-evening broadcast.",
    facts: [
      "Date: Address to the Nation, 15 August 1971.",
      "Treasury Secretary: John Connally; Fed Chair: Arthur Burns.",
      "Source: Federal Reserve History; full transcript via the American Presidency Project.",
    ],
    source: "Federal Reserve History",
    sourceUrl: "https://www.federalreservehistory.org/essays/gold-convertibility-ends",
    tags: ["nixon", "bretton-woods", "monetary"],
    icon: "◈",
    sentiment: "Analytical",
    impactLevel: "high",
  },
  {
    externalId: "lib-hist-cuban-missile",
    categorySlug: "geopolitics",
    contentType: "historical",
    author: "Robert F. Kennedy",
    historicalDate: "1962",
    headline: "Thirteen Days: the closest the world came to nuclear war",
    summary: "Between 16 and 28 October 1962, the discovery of Soviet missiles in Cuba brought the US and USSR within hours of nuclear exchange. Kennedy's quarantine and back-channel diplomacy averted it.",
    whyItMatters: "The crisis remains the canonical case study in escalation management, signalling, and crisis decision-making — taught at every staff college and replayed in every modern flashpoint analysis.",
    facts: [
      "Source: Robert F. Kennedy, Thirteen Days: A Memoir of the Cuban Missile Crisis, W.W. Norton, 1969.",
      "Soviet warheads on the island: 158, including 90+ tactical weapons declassified after 1991.",
      "Resolved by secret agreement to remove US Jupiter missiles from Turkey.",
    ],
    source: "Kennedy, Thirteen Days; Office of the Historian",
    sourceUrl: "https://history.state.gov/milestones/1961-1968/cuban-missile-crisis",
    tags: ["cold-war", "nuclear", "diplomacy"],
    icon: "◈",
    sentiment: "Cautionary",
    impactLevel: "high",
  },
  {
    externalId: "lib-hist-suez-1956",
    categorySlug: "geopolitics",
    contentType: "historical",
    author: "Office of the Historian, US State Department",
    historicalDate: "1956",
    headline: "Suez 1956: the moment Britain learned the limits of empire",
    summary: "When Britain, France and Israel attacked Egypt to retake the nationalised Suez Canal, US President Eisenhower forced their withdrawal through Treasury pressure on sterling.",
    whyItMatters: "The episode marked the formal end of British great-power autonomy and the dollar's emergence as a coercive instrument — the playbook for every subsequent financial sanction.",
    facts: [
      "Crisis dates: 29 October – 7 November 1956.",
      "Sterling-dollar reserve drain: ~$280m in early November; UK reserves fell 15%.",
      "Source: US Office of the Historian, FRUS 1955–1957, Vol. XVI.",
    ],
    source: "FRUS 1955–1957 Vol. XVI",
    sourceUrl: "https://history.state.gov/historicaldocuments/frus1955-57v16",
    tags: ["suez", "sterling", "post-imperial"],
    icon: "◈",
    sentiment: "Analytical",
    impactLevel: "medium",
  },
  {
    externalId: "lib-hist-deng-1978",
    categorySlug: "geopolitics",
    contentType: "historical",
    author: "Ezra Vogel",
    historicalDate: "1978",
    headline: "Deng's reform: the largest poverty reduction in history begins",
    summary: "At the Third Plenary Session of the 11th Central Committee, December 1978, Deng Xiaoping inaugurated ‘Reform and Opening Up’ — the policy turn that lifted ~800 million people out of extreme poverty.",
    whyItMatters: "The episode reframed development economics: a Leninist party demonstrated that authoritarian capitalism could deliver the fastest sustained growth in recorded history, complicating every Western theory of modernisation.",
    facts: [
      "Source: Ezra Vogel, Deng Xiaoping and the Transformation of China, Belknap/Harvard, 2011.",
      "World Bank: China's extreme-poverty rate fell from ~88% (1981) to <1% (2019).",
      "Plenary dates: 18–22 December 1978.",
    ],
    source: "Vogel (2011); World Bank Poverty data",
    sourceUrl: "https://data.worldbank.org/topic/poverty?locations=CN",
    tags: ["deng", "china", "reform"],
    icon: "◈",
    sentiment: "Analytical",
    impactLevel: "high",
  },
  {
    externalId: "lib-hist-glassteagall",
    categorySlug: "finance",
    contentType: "historical",
    author: "US Senate Banking Committee",
    historicalDate: "1933",
    headline: "Glass–Steagall: the wall between banks and markets",
    summary: "The Banking Act of 1933 separated commercial deposit-taking from investment banking and created federal deposit insurance — the architectural response to the bank failures of 1929–33.",
    whyItMatters: "Its partial repeal in 1999 (Gramm–Leach–Bliley) is widely cited as a precondition for the 2008 crisis. Every modern proposal to ‘ring-fence’ banks descends from this 1933 design.",
    facts: [
      "Sponsors: Senator Carter Glass (D-VA), Representative Henry Steagall (D-AL).",
      "Created the Federal Deposit Insurance Corporation (FDIC).",
      "Source: Federal Reserve History; FDIC archive.",
    ],
    source: "Federal Reserve History — Glass–Steagall",
    sourceUrl: "https://www.federalreservehistory.org/essays/glass-steagall-act",
    tags: ["banking", "regulation", "1933"],
    icon: "◈",
    sentiment: "Analytical",
    impactLevel: "medium",
  },
  {
    externalId: "lib-hist-internet-1969",
    categorySlug: "tech",
    contentType: "historical",
    author: "Leonard Kleinrock",
    historicalDate: "1969",
    headline: "ARPANET: the first packet sent",
    summary: "On 29 October 1969, a graduate student at UCLA typed ‘LO’ to a computer at Stanford before the system crashed. It was the first message sent over the network that became the internet.",
    whyItMatters: "ARPANET established packet-switching as the protocol of digital civilisation. Every subsequent layer — TCP/IP, the web, mobile, AI APIs — assumes this foundational architecture.",
    facts: [
      "Sender: Charley Kline (UCLA); receiver: Bill Duvall (SRI).",
      "Funded by the Advanced Research Projects Agency, US Department of Defense.",
      "Source: Internet Society oral history; Janet Abbate, Inventing the Internet (MIT Press, 1999).",
    ],
    source: "Internet Society — ARPANET",
    sourceUrl: "https://www.internetsociety.org/internet/history-internet/brief-history-internet/",
    tags: ["arpanet", "internet", "1969"],
    icon: "◈",
    sentiment: "Analytical",
    impactLevel: "medium",
  },

  // ── DEEP ESSAY / CULTURAL ────────────────────────────────────────────────
  {
    externalId: "lib-essay-mcluhan-medium",
    categorySlug: "society",
    contentType: "essay",
    author: "Marshall McLuhan",
    historicalDate: "1964",
    headline: "The medium is the message",
    summary: "McLuhan's central claim: the form of a communication technology reshapes social life independently of its content. Television transformed us not through what it broadcast but by being television.",
    whyItMatters: "The thesis is the operating premise of every serious media-effects argument from Postman to Zuboff. It is the lens through which to read social media, recommender systems, and generative AI.",
    facts: [
      "Source: Understanding Media: The Extensions of Man, McGraw-Hill, 1964.",
      "McLuhan was Director of the Centre for Culture and Technology, University of Toronto.",
      "Wired magazine named McLuhan its ‘patron saint’ at launch in 1993.",
    ],
    source: "McLuhan, Understanding Media",
    sourceUrl: "https://en.wikipedia.org/wiki/Understanding_Media",
    tags: ["mcluhan", "media", "technology"],
    icon: "❖",
    sentiment: "Analytical",
    impactLevel: "high",
  },
  {
    externalId: "lib-essay-borges-library",
    categorySlug: "society",
    contentType: "essay",
    author: "Jorge Luis Borges",
    historicalDate: "1941",
    headline: "The Library of Babel",
    summary: "Borges imagines a universe consisting of an infinite library containing every possible 410-page book — a thought experiment that anticipated information theory, the curse of dimensionality, and the LLM hallucination problem.",
    whyItMatters: "Engineers at OpenAI and DeepMind cite Borges directly. The Library is the first work of fiction to dramatise what total search across all generated text would actually feel like.",
    facts: [
      "Source: ‘La biblioteca de Babel’, in El jardín de senderos que se bifurcan, Sur, 1941.",
      "Republished in Ficciones (1944).",
      "Translation: Andrew Hurley, Penguin Classics, 1998.",
    ],
    source: "Borges, Ficciones (1944)",
    sourceUrl: "https://en.wikipedia.org/wiki/The_Library_of_Babel",
    tags: ["borges", "ai", "literature"],
    icon: "❖",
    sentiment: "Reflective",
    impactLevel: "medium",
  },
  {
    externalId: "lib-essay-orwell-language",
    categorySlug: "society",
    contentType: "essay",
    author: "George Orwell",
    historicalDate: "1946",
    headline: "Politics and the English language",
    summary: "Orwell's six-rule essay argues that vague, jargon-laden prose is not an aesthetic failure but a political one: imprecise language enables imprecise thought, which is the ground of bad governance.",
    whyItMatters: "The essay is the canonical reference for media literacy programmes, editorial style guides, and AI-output evaluation. Its diagnosis of ‘dying metaphors’ applies uncomfortably to modern slop content.",
    facts: [
      "Source: Horizon, April 1946.",
      "Six rules conclude the essay; the sixth is: ‘Break any of these rules sooner than say anything outright barbarous.’",
      "Reprinted in Shooting an Elephant and Other Essays, 1950.",
    ],
    source: "Orwell, Politics and the English Language",
    sourceUrl: "https://www.orwell.ru/library/essays/politics/english/e_polit/",
    tags: ["orwell", "language", "politics"],
    icon: "❖",
    sentiment: "Critical",
    impactLevel: "medium",
  },
  {
    externalId: "lib-essay-dostoevsky-grand-inquisitor",
    categorySlug: "society",
    contentType: "essay",
    author: "Fyodor Dostoevsky",
    historicalDate: "1880",
    headline: "The Grand Inquisitor",
    summary: "In Book V of The Brothers Karamazov, the Grand Inquisitor argues that humanity wants ‘miracle, mystery and authority’, not freedom — that institutions trade liberty for security, and most people accept the bargain.",
    whyItMatters: "The chapter is the most concentrated argument against benevolent paternalism in Western literature. It is read today against algorithmic curation, surveillance capitalism, and AI safety governance.",
    facts: [
      "Source: The Brothers Karamazov, Book V, Chapter 5, serialised 1879–80, The Russian Messenger.",
      "Standard translation: Pevear & Volokhonsky, Farrar, Straus and Giroux, 1990.",
      "Dostoevsky died two months after the novel's completion.",
    ],
    source: "Dostoevsky, The Brothers Karamazov",
    sourceUrl: "https://www.gutenberg.org/ebooks/28054",
    tags: ["dostoevsky", "freedom", "authority"],
    icon: "❖",
    sentiment: "Reflective",
    impactLevel: "high",
  },
  {
    externalId: "lib-essay-kafka-bureaucracy",
    categorySlug: "society",
    contentType: "essay",
    author: "Franz Kafka",
    historicalDate: "1925",
    headline: "Before the Law",
    summary: "Kafka's parable, embedded in The Trial, depicts a man who waits his whole life for permission to enter a door that was made only for him. The doorkeeper closes it as he dies.",
    whyItMatters: "The parable defines ‘Kafkaesque’ in a way no academic essay can: not a description of villains but of systems whose rules are incomprehensible to those they govern. A handbook for understanding modern algorithmic refusal.",
    facts: [
      "Source: ‘Vor dem Gesetz’, first published 1915 in the Selbstwehr weekly; embedded in Der Process, posthumously published 1925 by Max Brod.",
      "Translation: Willa and Edwin Muir, 1937.",
      "Kafka requested all his manuscripts be burned; Brod ignored him.",
    ],
    source: "Kafka, The Trial",
    sourceUrl: "https://en.wikipedia.org/wiki/Before_the_Law",
    tags: ["kafka", "bureaucracy", "power"],
    icon: "❖",
    sentiment: "Cautionary",
    impactLevel: "medium",
  },
  {
    externalId: "lib-essay-leguin-ones-walk-away",
    categorySlug: "society",
    contentType: "essay",
    author: "Ursula K. Le Guin",
    historicalDate: "1973",
    headline: "The Ones Who Walk Away from Omelas",
    summary: "Le Guin's parable describes a utopian city whose perfect happiness depends on the perpetual misery of a single hidden child. Most citizens accept the bargain. A few walk away.",
    whyItMatters: "The story is the most precise allegory in English for any system that externalises its costs — from cobalt mining to data labelling to climate inaction. It refuses the comfort of resolution.",
    facts: [
      "Source: New Dimensions 3, Robert Silverberg ed., 1973.",
      "Won the Hugo Award for Best Short Story in 1974.",
      "Reprinted in The Wind's Twelve Quarters, Harper & Row, 1975.",
    ],
    source: "Le Guin, The Wind's Twelve Quarters",
    sourceUrl: "https://en.wikipedia.org/wiki/The_Ones_Who_Walk_Away_from_Omelas",
    tags: ["le-guin", "ethics", "fiction"],
    icon: "❖",
    sentiment: "Reflective",
    impactLevel: "medium",
  },

  // ── GEOPOLITICAL SIGNAL ─────────────────────────────────────────────────
  {
    externalId: "lib-signal-rare-earths",
    categorySlug: "geopolitics",
    contentType: "geopolitical",
    headline: "Rare-earth concentration: the chokepoint nobody wants to fix",
    summary: "China processes ~85% of global rare-earth elements and refines >90% of heavy rare earths — inputs essential for EV motors, wind turbines, and precision-guided munitions.",
    whyItMatters: "Western diversification programmes (US DPA, EU Critical Raw Materials Act) target a 2030 horizon. Until then, every clean-energy and defence procurement decision runs through a single supplier nation.",
    facts: [
      "Source: USGS Mineral Commodity Summaries, 2024.",
      "China share of refining: ~85% (light REE), ~99% (heavy REE).",
      "EU Critical Raw Materials Act adopted March 2024; US DPA Title III investments since 2020.",
    ],
    source: "USGS Mineral Commodity Summaries 2024",
    sourceUrl: "https://pubs.usgs.gov/periodicals/mcs2024/mcs2024-rare-earths.pdf",
    tags: ["rare-earths", "supply-chain", "china"],
    icon: "◈",
    sentiment: "Cautionary",
    impactLevel: "high",
  },
  {
    externalId: "lib-signal-strait-hormuz",
    categorySlug: "geopolitics",
    contentType: "geopolitical",
    headline: "Strait of Hormuz: 20% of global oil through a 21-mile channel",
    summary: "The Strait of Hormuz between Iran and Oman carries roughly one-fifth of global petroleum liquids — about 20 million barrels per day — through a shipping lane two miles wide in each direction.",
    whyItMatters: "No alternative route can replace Hormuz capacity in the short term. Any closure would impose immediate, large supply shocks on countries with no diversified suppliers — particularly in Asia.",
    facts: [
      "Source: US Energy Information Administration, World Oil Transit Chokepoints, 2023.",
      "~76% of crude transiting Hormuz heads to Asian markets (China, India, Japan, South Korea).",
      "Shipping lane width: ~2 nautical miles per direction with a 2-nm buffer.",
    ],
    source: "US EIA — World Oil Transit Chokepoints",
    sourceUrl: "https://www.eia.gov/international/analysis/special-topics/World_Oil_Transit_Chokepoints",
    tags: ["energy", "chokepoint", "iran"],
    icon: "◈",
    sentiment: "Cautionary",
    impactLevel: "high",
  },
  {
    externalId: "lib-signal-semiconductor-tsmc",
    categorySlug: "tech",
    contentType: "geopolitical",
    headline: "Leading-edge chips: a single firm, a single island",
    summary: "TSMC fabricates approximately 90% of the world's most advanced (sub-7nm) logic chips at facilities concentrated in Taiwan — the densest concentration of strategic-industrial capability on Earth.",
    whyItMatters: "Every modern AI accelerator, smartphone SoC and advanced military system depends on this single supply node. Diversification programmes (US CHIPS Act, EU Chips Act) will take a decade to materially shift the balance.",
    facts: [
      "Source: TrendForce; Boston Consulting Group, ‘Strengthening the Global Semiconductor Supply Chain in an Uncertain Era’, 2021.",
      "TSMC Arizona Fab 21 began limited 4nm production in late 2024.",
      "US CHIPS and Science Act: $52.7bn appropriation, signed August 2022.",
    ],
    source: "TrendForce; BCG/SIA Report",
    sourceUrl: "https://www.semiconductors.org/wp-content/uploads/2021/05/BCG-x-SIA-Strengthening-the-Global-Semiconductor-Value-Chain-April-2021_1.pdf",
    tags: ["semiconductors", "taiwan", "tsmc"],
    icon: "△",
    sentiment: "Analytical",
    impactLevel: "high",
  },

  // ── MARKET SIGNAL ───────────────────────────────────────────────────────
  {
    externalId: "lib-market-yield-curve",
    categorySlug: "finance",
    contentType: "market_signal",
    headline: "The yield curve: recession indicator with eight-for-eight record",
    summary: "Inversions of the US 10-year/2-year Treasury yield spread have preceded each of the last eight US recessions, with no false positives since 1955.",
    whyItMatters: "The current cycle's inversion (July 2022 – September 2024) was the longest on record, yet the recession remained delayed. Whether the indicator has lost predictive power or merely the lag has lengthened is the central macro debate.",
    facts: [
      "Source: Federal Reserve Bank of San Francisco, Working Paper 2018-07, Bauer & Mertens.",
      "Recession lead time: 6–24 months historically.",
      "Series: FRED T10Y2Y; daily.",
    ],
    source: "FRBSF; FRED",
    sourceUrl: "https://www.frbsf.org/research-and-insights/publications/working-papers/2018/07/economic-forecasts-with-yield-curve/",
    tags: ["yield-curve", "macro", "recession"],
    icon: "◇",
    sentiment: "Cautionary",
    impactLevel: "high",
  },
  {
    externalId: "lib-market-buffett-indicator",
    categorySlug: "finance",
    contentType: "market_signal",
    author: "Warren Buffett",
    headline: "The Buffett Indicator at historical extremes",
    summary: "The ratio of total US stock market capitalisation to GDP — popularised by Buffett in a 2001 Fortune essay as ‘probably the best single measure of where valuations stand at any given moment’ — sits well above its post-WWII average.",
    whyItMatters: "The indicator is descriptive rather than predictive on short horizons, but elevated readings have historically corresponded to lower 10-year forward equity returns.",
    facts: [
      "Source: Warren Buffett & Carol Loomis, ‘Mr. Buffett on the Stock Market’, Fortune, 22 November 1999 (online 2001).",
      "Long-run average (1971–2010): ~0.85; latest readings well above 1.5.",
      "Underlying series: Wilshire 5000 / GDP, FRED.",
    ],
    source: "Buffett, Fortune (1999); FRED",
    sourceUrl: "https://fred.stlouisfed.org/graph/?g=qLC",
    tags: ["valuation", "buffett", "macro"],
    icon: "◇",
    sentiment: "Cautionary",
    impactLevel: "medium",
  },
  {
    externalId: "lib-market-hyman-minsky",
    categorySlug: "finance",
    contentType: "market_signal",
    author: "Hyman Minsky",
    historicalDate: "1986",
    headline: "Stability is destabilising",
    summary: "Minsky's financial instability hypothesis: long periods of economic calm encourage households, firms and banks to take on more debt, until a small shock triggers cascading deleveraging — a ‘Minsky moment’.",
    whyItMatters: "Ignored by mainstream macro until 2008, Minsky's framework now anchors most serious analysis of credit cycles, real estate bubbles, and the limits of central bank stabilisation.",
    facts: [
      "Source: Stabilizing an Unstable Economy, Yale University Press, 1986.",
      "‘Minsky moment’ coined by Paul McCulley (PIMCO) in 1998 during the Russian default.",
      "Minsky was a professor at Washington University in St. Louis.",
    ],
    source: "Minsky, Stabilizing an Unstable Economy",
    sourceUrl: "https://www.levyinstitute.org/scholars/hyman-p-minsky",
    tags: ["minsky", "credit", "instability"],
    icon: "◇",
    sentiment: "Cautionary",
    impactLevel: "high",
  },

  // ── CULTURE / SOCIETY ───────────────────────────────────────────────────
  {
    externalId: "lib-culture-attention-economy",
    categorySlug: "society",
    contentType: "culture",
    author: "Herbert A. Simon",
    historicalDate: "1971",
    headline: "A wealth of information creates a poverty of attention",
    summary: "Three decades before social media, Nobel laureate Herbert Simon warned that the scarce resource in an information-rich world would not be data but human attention — and that institutions would have to be redesigned around its allocation.",
    whyItMatters: "Simon's framing predicted the entire economic logic of the platform era. It is the single sharpest formulation in the literature on engagement and its discontents.",
    facts: [
      "Source: Herbert A. Simon, ‘Designing Organizations for an Information-Rich World’, in M. Greenberger (ed.), Computers, Communications, and the Public Interest (Johns Hopkins, 1971).",
      "Simon won the Nobel Memorial Prize in Economics in 1978.",
      "Foundational text of behavioural economics and organisational theory.",
    ],
    source: "Simon (1971); Johns Hopkins",
    sourceUrl: "https://digitalcollections.library.cmu.edu/awweb/awarchive?type=file&item=33748",
    tags: ["simon", "attention", "information"],
    icon: "◎",
    sentiment: "Analytical",
    impactLevel: "high",
  },
  {
    externalId: "lib-culture-tocqueville",
    categorySlug: "society",
    contentType: "culture",
    author: "Alexis de Tocqueville",
    historicalDate: "1840",
    headline: "Democratic despotism: a soft and gentle servitude",
    summary: "Tocqueville's late warning in Volume II of Democracy in America: democracies can produce a new kind of unfreedom — paternalistic, comfortable, and total — in which citizens trade self-government for soft administration.",
    whyItMatters: "The passage is the locus classicus for every contemporary critique of nudge-state paternalism, platform governance, and the administrative state. Read alongside Foucault, it predicts our present.",
    facts: [
      "Source: De la démocratie en Amérique, Vol. II, Part IV, Chapter 6 (1840).",
      "Translation: Harvey Mansfield & Delba Winthrop, University of Chicago Press, 2000.",
      "Tocqueville toured the United States 1831–32 as a French government commissioner.",
    ],
    source: "Tocqueville, Democracy in America II",
    sourceUrl: "https://oll.libertyfund.org/titles/tocqueville-democracy-in-america-historical-critical-edition-vol-4",
    tags: ["tocqueville", "democracy", "freedom"],
    icon: "◎",
    sentiment: "Cautionary",
    impactLevel: "medium",
  },

  // ── TECHNOLOGY (frontier) ───────────────────────────────────────────────
  {
    externalId: "lib-tech-turing-1950",
    categorySlug: "tech",
    contentType: "technology",
    author: "Alan Turing",
    historicalDate: "1950",
    headline: "Computing Machinery and Intelligence",
    summary: "Turing proposed the imitation game — now called the Turing Test — and rebutted nine objections to the proposition that machines could think. The paper opened the field of AI as a serious philosophical and engineering programme.",
    whyItMatters: "Every modern argument about machine cognition, alignment, and consciousness still cites this 28-page paper. Its predictions about memory and processing power were strikingly accurate.",
    facts: [
      "Source: Alan Turing, ‘Computing Machinery and Intelligence’, Mind, Vol. LIX, No. 236, October 1950.",
      "Turing predicted machines would have ~10⁹ bits of storage by 2000 (correct order of magnitude).",
      "DOI: 10.1093/mind/LIX.236.433",
    ],
    source: "Turing (1950), Mind",
    sourceUrl: "https://academic.oup.com/mind/article/LIX/236/433/986238",
    tags: ["turing", "ai", "consciousness"],
    icon: "△",
    sentiment: "Analytical",
    impactLevel: "high",
  },
  {
    externalId: "lib-tech-shannon-1948",
    categorySlug: "tech",
    contentType: "technology",
    author: "Claude Shannon",
    historicalDate: "1948",
    headline: "A Mathematical Theory of Communication",
    summary: "Claude Shannon's two-part Bell Labs paper defined information as a quantitative concept (the bit) and proved theoretical limits for compression and noisy-channel transmission — the entire mathematical foundation of digital civilisation.",
    whyItMatters: "Without Shannon, no internet, no compression, no LLMs. His theory underwrites every byte that moves and every token that is sampled.",
    facts: [
      "Source: Bell System Technical Journal, Vol. 27, July & October 1948.",
      "Shannon's MIT master's thesis (1937) is also the founding document of digital circuit design.",
      "He worked at Bell Labs from 1941 to 1972.",
    ],
    source: "Shannon (1948), BSTJ",
    sourceUrl: "https://people.math.harvard.edu/~ctm/home/text/others/shannon/entropy/entropy.pdf",
    tags: ["shannon", "information", "foundations"],
    icon: "△",
    sentiment: "Analytical",
    impactLevel: "high",
  },
];

async function run() {
  // Auto-set publishedAt: spread across the last 14 days for visual variety
  const now = Date.now();
  const rows = LIBRARY.map((s, i) => {
    const yearsAgo = s.publishedYearsAgo ?? 0;
    const daysOffset = (i % 14);
    const publishedAt = new Date(now - yearsAgo * 365.25 * 86400_000 - daysOffset * 86400_000);
    return {
      externalId: s.externalId,
      categorySlug: s.categorySlug,
      headline: s.headline,
      summary: s.summary,
      whyItMatters: s.whyItMatters,
      facts: s.facts,
      source: s.source,
      sourceUrl: s.sourceUrl,
      readTime: `${Math.max(1, Math.round(s.summary.length / 600))} min`,
      sentiment: s.sentiment,
      impactLevel: s.impactLevel ?? "medium" as const,
      icon: s.icon,
      isFeatured: false,
      contentType: s.contentType,
      author: s.author ?? null,
      historicalDate: s.historicalDate ?? null,
      tags: s.tags,
      imageUrl: s.imageUrl ?? null,
      publishedAt,
    };
  });

  let inserted = 0, updated = 0;
  for (const row of rows) {
    const result = await db.insert(articlesTable).values(row as any)
      .onConflictDoUpdate({
        target: articlesTable.externalId,
        set: {
          headline: row.headline,
          summary: row.summary,
          whyItMatters: row.whyItMatters,
          facts: row.facts,
          source: row.source,
          sourceUrl: row.sourceUrl,
          contentType: row.contentType as any,
          author: row.author,
          historicalDate: row.historicalDate,
          tags: row.tags,
          icon: row.icon,
          impactLevel: row.impactLevel,
        },
      }).returning({ id: articlesTable.id });
    if (result.length) inserted++;
  }

  const totals = await db.select({ count: sql<number>`count(*)` }).from(articlesTable);
  console.log(`✓ Library seeded: ${inserted} entries upserted. Total articles in DB: ${totals[0].count}`);
  process.exit(0);
}

run().catch(e => { console.error(e); process.exit(1); });
